name: langgraph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - langgraph>=0.0.15
    - langchain>=0.1.0
    - openai>=1.3.0
    - python-dotenv>=0.19.0
    - pydantic>=2.0.0
    - typing-extensions>=4.5.0
    - python-json-logger>=2.0.7
    - structlog>=24.1.0
    - pytest>=7.0.0
    - pytest-asyncio>=0.23.0
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.1.0
    - mkdocs>=1.5.0
    - mkdocs-material>=9.5.0
